In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv("/content/twitter_validation.csv",encoding="ISO-8859-1",header=None)
df.columns=["Id","Location","Target","Text"]
print(df)

       Id             Location      Target  \
0    3364             Facebook  Irrelevant
1     352               Amazon     Neutral
2    8312            Microsoft    Negative
3    4371                CS-GO    Negative
4    4433               Google     Neutral
..    ...                  ...         ...
995  4891  GrandTheftAuto(GTA)  Irrelevant
996  4359                CS-GO  Irrelevant
997  2652          Borderlands    Positive
998  8069            Microsoft    Positive
999  6960      johnson&johnson     Neutral

                                                  Text
0    I mentioned on Facebook that I was struggling ...
1    BBC News - Amazon boss Jeff Bezos rejects clai...
2    @Microsoft Why do I pay for WORD when it funct...
3    CSGO matchmaking is so full of closet hacking,...
4    Now the President is slapping Americans in the...
..                                                 ...
995  â­ï¸ Toronto is the arts and culture capital...
996  tHIS IS ACTUALLY A GOOD MOVE TOT BRING MORE VI...
997  Today sucked so itâs time to drink wine n pl...
998  Bought a fraction of Microsoft today. Small wins.
999  Johnson & Johnson to stop selling talc baby po...

[1000 rows x 4 columns]

In [ ]:
import nltk
from nltk.stem import WordNetLemmatizer

In [ ]:
df.drop(df.index[(df['Target']=="Irrelevant")],axis=0,inplace=True)

In [ ]:
df

,Id,Location,Target,Text
1,352,Amazon,Neutral,BBC News - Amazon boss Jeff Bezos rejects clai...
2,8312,Microsoft,Negative,@Microsoft Why do I pay for WORD when it funct...
3,4371,CS-GO,Negative,"CSGO matchmaking is so full of closet hacking,..."
4,4433,Google,Neutral,Now the President is slapping Americans in the...
5,6273,FIFA,Negative,Hi @EAHelp Iâve had Madeleine McCann in my c...
...,...,...,...,...
993,314,Amazon,Negative,Please explain how this is possible! How can t...
994,9701,PlayStation5(PS5),Positive,Good on Sony. As much as I want to see the new...
997,2652,Borderlands,Positive,Today sucked so itâs time to drink wine n pl...
998,8069,Microsoft,Positive,Bought a fraction of Microsoft today. Small wins.
999,6960,johnson&johnson,Neutral,Johnson & Johnson to stop selling talc baby po...

In [ ]:
df.reset_index(drop=True,inplace=True)

In [ ]:
df.drop(["Id","Location"],axis=1,inplace=True)

In [ ]:
df

       Target                                               Text
0     Neutral  BBC News - Amazon boss Jeff Bezos rejects clai...
1    Negative  @Microsoft Why do I pay for WORD when it funct...
2    Negative  CSGO matchmaking is so full of closet hacking,...
3     Neutral  Now the President is slapping Americans in the...
4    Negative  Hi @EAHelp Iâve had Madeleine McCann in my c...
..        ...                                                ...
823  Negative  Please explain how this is possible! How can t...
824  Positive  Good on Sony. As much as I want to see the new...
825  Positive  Today sucked so itâs time to drink wine n pl...
826  Positive  Bought a fraction of Microsoft today. Small wins.
827   Neutral  Johnson & Johnson to stop selling talc baby po...

[828 rows x 2 columns]

In [ ]:
df["Target"]=df["Target"].map({'Positive':1,'Negative':-1,'Neutral':0})
df

     Target                                               Text
0         0  BBC News - Amazon boss Jeff Bezos rejects clai...
1        -1  @Microsoft Why do I pay for WORD when it funct...
2        -1  CSGO matchmaking is so full of closet hacking,...
3         0  Now the President is slapping Americans in the...
4        -1  Hi @EAHelp Iâve had Madeleine McCann in my c...
..      ...                                                ...
823      -1  Please explain how this is possible! How can t...
824       1  Good on Sony. As much as I want to see the new...
825       1  Today sucked so itâs time to drink wine n pl...
826       1  Bought a fraction of Microsoft today. Small wins.
827       0  Johnson & Johnson to stop selling talc baby po...

[828 rows x 2 columns]

In [ ]:
import nltk

In [ ]:

nltk.download('wordnet')
nltk.download('stopwords')
nltk.download('punkt')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

True

In [ ]:
#assigning the test column into a variable
tweets=df.Text
tweets

0      BBC News - Amazon boss Jeff Bezos rejects clai...
1      @Microsoft Why do I pay for WORD when it funct...
2      CSGO matchmaking is so full of closet hacking,...
3      Now the President is slapping Americans in the...
4      Hi @EAHelp Iâve had Madeleine McCann in my c...
                             ...
823    Please explain how this is possible! How can t...
824    Good on Sony. As much as I want to see the new...
825    Today sucked so itâs time to drink wine n pl...
826    Bought a fraction of Microsoft today. Small wins.
827    Johnson & Johnson to stop selling talc baby po...
Name: Text, Length: 828, dtype: object

In [ ]:
from nltk import TweetTokenizer
tk=TweetTokenizer()
tweet=tweets.apply(lambda x: tk.tokenize(x)).apply(lambda x:" ".join(x))
tweet

0      BBC News - Amazon boss Jeff Bezos rejects clai...
1      @Microsoft Why do I pay for WORD when it funct...
2      CSGO matchmaking is so full of closet hacking ...
3      Now the President is slapping Americans in the...
4      Hi @EAHelp Iâ   ve had Madeleine McCann in m...
                             ...
823    Please explain how this is possible ! How can ...
824    Good on Sony . As much as I want to see the ne...
825    Today sucked so itâ   s time to drink wine n...
826    Bought a fraction of Microsoft today . Small w...
827    Johnson & Johnson to stop selling talc baby po...
Name: Text, Length: 828, dtype: object

In [ ]:
tweet=tweet.str.replace(r'[^a-zA-Z\s]',"",regex=True)
tweet

0      BBC News  Amazon boss Jeff Bezos rejects claim...
1      Microsoft Why do I pay for WORD when it functi...
2      CSGO matchmaking is so full of closet hacking ...
3      Now the President is slapping Americans in the...
4      Hi EAHelp I   ve had Madeleine McCann in my ce...
                             ...
823    Please explain how this is possible  How can t...
824    Good on Sony  As much as I want to see the new...
825    Today sucked so it   s time to drink wine n pl...
826    Bought a fraction of Microsoft today  Small wins
827    Johnson  Johnson to stop selling talc baby pow...
Name: Text, Length: 828, dtype: object

In [ ]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [ ]:
from nltk.tokenize import word_tokenize
tweet=tweet.apply(lambda x: ' '.join([i for i in word_tokenize(x) if len(i)>=3]))
tweet

0      BBC News Amazon boss Jeff Bezos rejects claims...
1      Microsoft Why pay for WORD when functions poor...
2      CSGO matchmaking full closet hacking its truly...
3      Now the President slapping Americans the face ...
4      EAHelp had Madeleine McCann cellar for the pas...
                             ...
823    Please explain how this possible How can they ...
824    Good Sony much want see the new whats going ri...
825    Today sucked time drink wine play borderlands ...
826           Bought fraction Microsoft today Small wins
827    Johnson Johnson stop selling talc baby powder ...
Name: Text, Length: 828, dtype: object

In [ ]:
from nltk.stem import SnowballStemmer
stemmer=SnowballStemmer('english')
tweet=tweet.apply(lambda x: [stemmer.stem(i.lower()) for i in tk.tokenize(x)]).apply(lambda x:' '.join(x))
tweet

0      bbc news amazon boss jeff bezo reject claim co...
1      microsoft whi pay for word when function poor ...
2        csgo matchmak full closet hack it truli aw game
3      now the presid slap american the face that rea...
4      eahelp had madelein mccann cellar for the past...
                             ...
823    pleas explain how this possibl how can they le...
824    good soni much want see the new what go right ...
825    today suck time drink wine play borderland unt...
826            bought fraction microsoft today small win
827    johnson johnson stop sell talc babi powder and...
Name: Text, Length: 828, dtype: object

In [ ]:
from nltk.corpus import stopwords
stop=stopwords.words("english")
tweet=tweet.apply(lambda x:[i for i in tk.tokenize(x) if i not in stop]).apply(lambda x: ' '.join(x))
tweet

0      bbc news amazon boss jeff bezo reject claim co...
1      microsoft whi pay word function poor samsungus...
2           csgo matchmak full closet hack truli aw game
3      presid slap american face realli commit unlaw ...
4      eahelp madelein mccann cellar past year littl ...
                             ...
823    pleas explain possibl let compani overcharg sc...
824     good soni much want see new go right much import
825    today suck time drink wine play borderland sun...
826            bought fraction microsoft today small win
827    johnson johnson stop sell talc babi powder can...
Name: Text, Length: 828, dtype: object

In [ ]:
#vectorization
from sklearn.feature_extraction.text import TfidfVectorizer
vec=TfidfVectorizer()
train_data=vec.fit_transform(tweet)
print(train_data)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 9443 stored elements and shape (828, 3577)>
  Coords	Values
  (0, 252)	0.3064011843880816
  (0, 2006)	0.24595464630679434
  (0, 87)	0.17917774280463503
  (0, 347)	0.2664481959239154
  (0, 1583)	0.2887217053500984
  (0, 282)	0.3064011843880816
  (0, 2573)	0.3064011843880816
  (0, 510)	0.25177701032680316
  (0, 566)	0.2038742622481763
  (0, 20)	0.2664481959239154
  (0, 1722)	0.1559715141695495
  (0, 829)	0.2887217053500984
  (0, 700)	0.3064011843880816
  (0, 253)	0.3064011843880816
  (1, 1876)	0.24727733554840492
  (1, 3442)	0.26204240398103884
  (1, 2166)	0.31254912613573693
  (1, 3485)	0.36541091255151514
  (1, 1092)	0.40539931027165166
  (1, 2389)	0.3820075971414484
  (1, 2688)	0.40539931027165166
  (1, 500)	0.40539931027165166
  (2, 661)	0.30796681055647745
  (2, 1824)	0.39556320810766255
  (2, 1089)	0.37837758706381164
  :	:
  (825, 696)	0.231545364016424
  (825, 345)	0.22978748223163353
  (825, 3187)	0.2560324519806264
  (825, 3197)	0.33956550602972524
  (825, 554)	0.2506669186044354
  (825, 1285)	0.28066825180478033
  (825, 3457)	0.35498831199314024
  (825, 821)	0.3767255361239052
  (825, 3032)	0.3767255361239052
  (826, 1876)	0.3091494903313533
  (826, 3187)	0.34445872015913015
  (826, 3454)	0.3568536179525714
  (826, 350)	0.41647876257497546
  (826, 2863)	0.4775910970452282
  (826, 1067)	0.5068357351603294
  (827, 1599)	0.42109445764962544
  (827, 220)	0.2532901395148254
  (827, 2407)	0.2653117914701689
  (827, 2986)	0.246633752733122
  (827, 3071)	0.30461548664110993
  (827, 2745)	0.2811863447474052
  (827, 422)	0.29552696613061546
  (827, 1593)	0.3502915287759717
  (827, 2620)	0.3502915287759717
  (827, 1374)	0.3502915287759717

In [ ]:
y=df["Target"].values
y

array([ 0, -1, -1,  0, -1,  1,  1,  1, -1,  1,  1, -1,  0, -1,  1,  1, -1,
        1, -1, -1,  0, -1,  0,  0, -1, -1,  1,  1, -1,  1, -1,  0,  0,  1,
        0,  1,  0,  0,  0,  1,  0, -1, -1, -1,  0,  1, -1, -1,  1,  1,  1,
        1,  1, -1, -1,  1,  1, -1,  0, -1,  0, -1,  1, -1, -1,  1,  1,  1,
        0,  0,  0,  1,  1,  0,  1,  0, -1, -1,  0,  0, -1,  1, -1, -1, -1,
        0,  1,  0, -1,  1,  1,  0,  1,  0,  1, -1,  0,  0,  0, -1,  0, -1,
        0,  0,  1,  1,  0, -1, -1,  1, -1,  0, -1,  1,  0, -1,  0,  1,  0,
        1,  1,  0,  0,  0,  0,  1,  0,  1,  1, -1,  0,  0,  0,  0, -1,  0,
        1, -1,  0, -1,  0, -1, -1, -1,  1,  1,  1,  0,  0,  1,  0,  0,  0,
        1,  0, -1, -1,  0,  1,  1,  0,  1,  1,  0,  0, -1, -1, -1, -1,  1,
        0,  0,  1,  1,  1,  1, -1,  1,  1,  0, -1, -1, -1,  1,  1, -1, -1,
        1,  1, -1,  1,  1, -1,  1,  0, -1,  0,  0,  1, -1,  1,  1,  0,  1,
       -1, -1,  1,  1,  1,  1,  0,  0,  1, -1,  0,  1,  0, -1,  0,  0, -1,
        1,  1, -1,  0,  1,  0, -1,  0, -1,  1,  1, -1, -1, -1,  1, -1,  0,
        1,  0,  0, -1,  1, -1,  1, -1,  0,  0,  1, -1,  0, -1,  1, -1,  1,
        1,  1,  1,  1,  1, -1, -1,  1, -1,  0,  0,  0,  1,  0,  1, -1,  0,
        0,  0,  0, -1,  1, -1, -1,  1,  1,  0,  0, -1, -1, -1,  0,  1,  0,
       -1,  1,  0, -1, -1, -1,  1,  0,  0, -1,  1,  1,  0,  1,  0,  0,  1,
        1, -1,  0,  1, -1,  0, -1, -1,  1,  1,  1,  1,  0, -1,  0,  1,  0,
        1, -1, -1, -1,  1,  0,  1, -1,  0, -1,  1,  1,  1,  1,  0,  0,  0,
       -1,  1,  1,  0, -1,  1,  0, -1, -1, -1, -1, -1,  0,  0,  0,  1,  1,
       -1, -1,  0, -1,  0,  0, -1,  1, -1,  1,  1,  1,  0,  1,  0,  0, -1,
        1,  0,  0,  0,  0,  0,  0,  0,  0, -1, -1,  1,  1,  0, -1, -1,  1,
        1, -1,  1,  1,  1,  1,  1,  0, -1,  1,  0,  0,  1,  1,  1,  1,  0,
       -1, -1, -1, -1,  0,  1, -1, -1,  1,  1,  0,  0, -1, -1,  1,  0, -1,
       -1, -1,  0,  0,  1, -1, -1, -1,  0,  0,  0, -1, -1,  1, -1,  0, -1,
        0,  1, -1,  0,  1,  1, -1,  0,  0,  1, -1, -1,  0,  0, -1,  1, -1,
        0, -1, -1, -1,  1, -1,  1, -1,  1, -1, -1,  0, -1,  0, -1,  1, -1,
        0, -1, -1,  0,  0,  1, -1,  1,  0,  0,  0,  0, -1,  0,  0,  0, -1,
       -1,  0,  1,  0,  0, -1,  0,  1,  0,  0,  0,  0,  0,  1,  0,  1,  1,
        1,  0, -1,  1,  0,  0, -1,  1,  0,  0, -1,  0, -1,  0,  1, -1,  1,
       -1, -1,  0,  0,  0,  0,  1,  1,  1, -1, -1,  0,  1,  0,  0, -1,  1,
        1,  0,  1, -1, -1,  0,  1, -1,  1, -1,  0,  1,  1,  0,  0,  0,  1,
        0, -1,  0,  0, -1,  1, -1,  0,  1,  1,  1,  1,  0, -1,  0,  1,  1,
        1,  1,  1, -1,  0,  1,  0,  0, -1, -1, -1,  0,  1,  0, -1,  1,  1,
        1,  0,  1, -1,  0, -1,  0, -1,  0,  0,  1, -1,  1,  1,  0, -1,  0,
       -1, -1, -1, -1,  1,  1,  1,  1,  0, -1, -1,  1, -1, -1,  0,  0,  1,
        0, -1,  0,  1, -1,  0,  1, -1,  0,  0,  1, -1,  0, -1,  1,  1,  0,
        1,  0,  1, -1,  0,  0,  0,  1,  0,  0, -1,  1,  0, -1, -1,  0,  0,
        1, -1, -1, -1, -1,  1,  0,  0,  1,  0, -1,  1,  1, -1,  1,  1,  0,
       -1,  0,  1,  1, -1, -1, -1,  1, -1,  0, -1,  0,  0,  1,  1, -1,  0,
        1, -1, -1, -1, -1, -1, -1, -1, -1,  0, -1,  0,  0,  0,  1,  0,  0,
        0, -1,  0,  1,  0, -1, -1,  1,  0,  1,  0,  1,  0, -1,  1,  1,  1,
        1, -1, -1,  1,  0,  0,  0,  0,  0,  0, -1, -1, -1, -1,  1, -1,  0,
        1,  0, -1,  1,  1, -1,  1,  0,  0,  1, -1,  0, -1,  0,  1,  1,  0,
       -1,  1, -1, -1,  0, -1,  0, -1,  1,  0, -1, -1,  1,  1, -1,  0, -1,
        0,  0,  0,  0,  0,  0,  1,  0,  1,  1,  1, -1,  0,  1,  0,  1,  0,
        1,  0,  1,  0, -1, -1,  1,  1,  1,  1,  0, -1,  1,  1, -1, -1, -1,
        0,  1,  0,  1,  1,  0,  1, -1,  1,  1,  1,  0])

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(train_data,y,test_size=0.30)
print(x_train)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 6593 stored elements and shape (579, 3577)>
  Coords	Values
  (0, 510)	0.2037015218509233
  (0, 566)	0.16494555016076737
  (0, 3486)	0.15236305479596862
  (0, 630)	0.18468723142384816
  (0, 1599)	0.2980015559557162
  (0, 220)	0.17924922618303082
  (0, 2407)	0.18775674966801403
  (0, 3340)	0.18186354836059038
  (0, 3238)	0.2091395270917406
  (0, 172)	0.2037015218509233
  (0, 1063)	0.2037015218509233
  (0, 446)	0.18468723142384816
  (0, 424)	0.2091395270917406
  (0, 2083)	0.1422144351503396
  (0, 3224)	0.2037015218509233
  (0, 2087)	0.17681535046386104
  (0, 2584)	0.2234432031140041
  (0, 1249)	0.23359182275963308
  (0, 892)	0.23359182275963308
  (0, 2202)	0.24789549878189654
  (0, 805)	0.24789549878189654
  (0, 1338)	0.2091395270917406
  (0, 2200)	0.24789549878189654
  (1, 3506)	0.37428408455395523
  (1, 1056)	0.39353444098311385
  :	:
  (578, 998)	0.14660285224603595
  (578, 1686)	0.15868443183319847
  (578, 414)	0.1520914059913963
  (578, 931)	0.145362895624089
  (578, 221)	0.1569080559343239
  (578, 1924)	0.20076945040215666
  (578, 2464)	0.1520914059913963
  (578, 1698)	0.1520914059913963
  (578, 2732)	0.18532750425141742
  (578, 2819)	0.20076945040215666
  (578, 2360)	0.16937616881365586
  (578, 904)	0.18145774840081838
  (578, 2566)	0.21755260117754777
  (578, 985)	0.19477928460992786
  (578, 3378)	0.20810082081903733
  (578, 47)	0.23087413738665724
  (578, 463)	0.23087413738665724
  (578, 3108)	0.23087413738665724
  (578, 3564)	0.23087413738665724
  (578, 41)	0.23087413738665724
  (578, 905)	0.23087413738665724
  (578, 1145)	0.23087413738665724
  (578, 40)	0.23087413738665724
  (578, 3563)	0.23087413738665724
  (578, 1406)	0.23087413738665724

In [ ]:
from sklearn.svm import SVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
svm_model=SVC()
nb_model=MultinomialNB()
rf_model=RandomForestClassifier()
de_model=DecisionTreeClassifier()
lstmodel=[svm_model,nb_model,rf_model,de_model]

In [ ]:
from sklearn.metrics import confusion_matrix,classification_report
for i in lstmodel:
  print(i)
  i.fit(x_train,y_train)
  y_pred=i.predict(x_test)
  print("************************")
  print(classification_report(y_test,y_pred))
  print("*****************************")

SVC()
************************
              precision    recall  f1-score   support

          -1       0.49      0.77      0.60        65
           0       0.77      0.49      0.60        97
           1       0.65      0.63      0.64        87

    accuracy                           0.61       249
   macro avg       0.64      0.63      0.61       249
weighted avg       0.66      0.61      0.61       249

*****************************
MultinomialNB()
************************
              precision    recall  f1-score   support

          -1       0.47      0.78      0.59        65
           0       0.80      0.38      0.52        97
           1       0.62      0.67      0.64        87

    accuracy                           0.59       249
   macro avg       0.63      0.61      0.58       249
weighted avg       0.65      0.59      0.58       249

*****************************
RandomForestClassifier()
************************
              precision    recall  f1-score   support

          -1       0.43      0.71      0.54        65
           0       0.82      0.37      0.51        97
           1       0.59      0.67      0.62        87

    accuracy                           0.56       249
   macro avg       0.61      0.58      0.56       249
weighted avg       0.64      0.56      0.56       249

*****************************
DecisionTreeClassifier()
************************
              precision    recall  f1-score   support

          -1       0.36      0.37      0.36        65
           0       0.54      0.55      0.54        97
           1       0.54      0.52      0.53        87

    accuracy                           0.49       249
   macro avg       0.48      0.48      0.48       249
weighted avg       0.49      0.49      0.49       249

*****************************

In [ ]:
from sklearn.svm import LinearSVC
from sklearn.naive_bayes import MultinomialNB

models = [
    LinearSVC(),
    MultinomialNB()
]

In [ ]:
from sklearn.metrics import classification_report

for model in models:
    print(model)
    model.fit(x_train, y_train)
    y_pred = model.predict(x_test)
    print(classification_report(y_test, y_pred))
    print("-------------")

LinearSVC()
              precision    recall  f1-score   support

          -1       0.54      0.65      0.59        65
           0       0.72      0.56      0.63        97
           1       0.62      0.69      0.66        87

    accuracy                           0.63       249
   macro avg       0.63      0.63      0.62       249
weighted avg       0.64      0.63      0.63       249

-------------
MultinomialNB()
              precision    recall  f1-score   support

          -1       0.47      0.78      0.59        65
           0       0.80      0.38      0.52        97
           1       0.62      0.67      0.64        87

    accuracy                           0.59       249
   macro avg       0.63      0.61      0.58       249
weighted avg       0.65      0.59      0.58       249

-------------

#chatgpt version

In [ ]:
# =========================
# 1. Import Libraries
# =========================
import pandas as pd
import numpy as np
import nltk

# Download required datasets
nltk.download('punkt')
nltk.download('stopwords')

# =========================
# 2. Load Dataset
# =========================
df = pd.read_csv("/content/twitter_validation.csv", encoding="ISO-8859-1", header=None)
df.columns = ["Id", "Location", "Target", "Text"]

# =========================
# 3. Data Cleaning
# =========================

# Remove irrelevant rows
df = df[df["Target"] != "Irrelevant"]

# Reset index
df.reset_index(drop=True, inplace=True)

# Drop unnecessary columns
df.drop(["Id", "Location"], axis=1, inplace=True)

# Convert target labels to numeric
df["Target"] = df["Target"].map({
    'Positive': 1,
    'Negative': -1,
    'Neutral': 0
})

# =========================
# 4. Text Preprocessing
# =========================
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import SnowballStemmer

stop = set(stopwords.words("english"))
stemmer = SnowballStemmer('english')

# Lowercase
tweet = df["Text"].str.lower()

# Remove special characters
tweet = tweet.str.replace(r'[^a-zA-Z\s]', '', regex=True)

# Tokenization + Stopword Removal + Short word removal + Stemming
tweet = tweet.apply(lambda x: [
    stemmer.stem(word)
    for word in word_tokenize(x)
    if word not in stop and len(word) >= 3
])

# Join tokens back to sentence
tweet = tweet.apply(lambda x: " ".join(x))

# =========================
# 5. Vectorization (TF-IDF)
# =========================
from sklearn.feature_extraction.text import TfidfVectorizer

vec = TfidfVectorizer()
X = vec.fit_transform(tweet)

y = df["Target"].values

# =========================
# 6. Train-Test Split
# =========================
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# =========================
# 7. Model Training
# =========================
from sklearn.svm import LinearSVC
from sklearn.naive_bayes import MultinomialNB

models = {
    "Linear SVM": LinearSVC(),
    "Naive Bayes": MultinomialNB()
}

# =========================
# 8. Evaluation
# =========================
from sklearn.metrics import classification_report, accuracy_score

for name, model in models.items():
    print(f"\nModel: {name}")

    model.fit(x_train, y_train)
    y_pred = model.predict(x_test)

    print("Accuracy:", accuracy_score(y_test, y_pred))
    print(classification_report(y_test, y_pred))
    print("====================================")

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

Model: Linear SVM
Accuracy: 0.5341365461847389
              precision    recall  f1-score   support

          -1       0.53      0.52      0.53        79
           0       0.43      0.53      0.48        79
           1       0.67      0.55      0.60        91

    accuracy                           0.53       249
   macro avg       0.54      0.53      0.54       249
weighted avg       0.55      0.53      0.54       249

====================================

Model: Naive Bayes
Accuracy: 0.5502008032128514
              precision    recall  f1-score   support

          -1       0.54      0.54      0.54        79
           0       0.48      0.49      0.48        79
           1       0.63      0.60      0.62        91

    accuracy                           0.55       249
   macro avg       0.55      0.55      0.55       249
weighted avg       0.55      0.55      0.55       249

====================================